### ISSUE TITLE
1D Descriptor DMA Memory to Stream (MM2S), and Stream to Memory (S2MM) and Memory to Memory (MM2MM)

### ISSUE THREAD

**Issue by asultan123** [Sparkles-Qemu/qemu_system_integration#4]
Read the article on Descriptor DMAs [here](https://www.embedded.com/using-direct-memory-access-effectively-in-media-based-embedded-applications-part-2/), and develop 3 versions of the 1D descriptor based DMA. The 3 versions are the memory to stream, stream to memory and memory to memory DMAs. Note that memory to memory is just a composition of 2 memory to stream and stream to memory dmas which will now be abbreviated MM2S and S2MM. For simplicity, it is not necessary to model a separate SRAM component and hook it up to the DMAs. An SRAM can be modeled as just a pointer to an array passed to the DMA that the DMA either reads from or writes to (Ignore delays for reading and writing to the SRAM). For the Memory to Memory Descriptor 2 pointers will need to be passed. What distinguishes between the DMAs is whether is has an input stream port (S2MM), an output stream port (MM2S) or no ports (MM2MM). 
For all DMAs add an internal buffer of descriptors (these are basically instructions) that gets loaded automagically (You don't have to formally pass the descriptors in via a port). The DMA should keep track of what descriptor is currently being executed via local executeIndex variable that is incremented once the descriptor is completed (Transfer/Operation Concludes) Executing descriptors should occur every clock cycle with each cycle ideally involving a single transfer of one unit of data. Given the flexibility of the dmaConfig field of a descriptor, add a timed wait descriptors that forces the DMA to IDLE for a predetermined number of inputs defined by xCount and xModify. 
Provide an automated TestBench that validates the correct output of all the descriptor variants. Testcases should be generally simple and they should involve changing start addresses, xCount and xModify. 

**_It may be useful to create a parent GenericDMA object that observes descriptor execution and retirement. This is useful because that logic is common the all DMA variants. Execution details will be determined by the derived classes MM2S, S2MM. Please note that MM2MM is just a composition so it does not need to inherit from the GenericDMA base class._**

**Comment by JLonda** [comment]
@asultan123 the link to the pdf seems to be broken, would you mind fixing it?

**Comment by JLonda** [comment]
Notes doc: https://docs.google.com/document/d/1SFTKMTB76cBv1dtWCKreSIqzIJJriYDvv_n7qpJcG-s/edit?usp=sharing

**Comment by JLonda** [comment]
@asultan123 would you mind taking a look at how this is currently structured? It's using composition to reuse functionality of the base dma module. However, there is still a lot that will need to be repeated. What if instead of having a base module, we make just one dma module that has the ram and stream as in_out signals, and choose which direction to move the data based on a value in the dma config field. The MM2S and S2MM versions are practically identical, except for the direction of data flow.

**Comment by owenber123** [comment]
I just pushed progress on the DMA testbench.  I have an issue right now where systemC doesn't like when you drive a signal from two different modules even if they are sc_inout (im talking about the stream).  I think this is an easy fix I will try tonight after dinner or tomorrow morning.  I moved the majority of the SIM.cpp simulation code into the test bench for now because it is specific for the DMA.  I would appreciate it if someone could check the architecture of my testbench module for reassurance so I can continue confidently.  Thanks.

**Comment by JLonda** [comment]
Looks good so far. Though I'm not sure how the architecture of the testbench should look. @asultan123 any thoughts?

**Comment by owenber123** [comment]
I just pushed a working version of the test bench.
Right now it tests a single DMA MM2S instance and fails in the following states if:
Transferring: Stream is not accessed in ram correctly
Waiting/Suspended: If the stream changes from the last clock cycle

I plan on adding a S2MM DMA module and timing checks for the waiting and suspended states in the near future.

**Comment by owenber123** [comment]
I pushed MM2MM implementation.  It resides in DMA.cpp and is composed of two DMA instances, one MM2S and one S2MM.  I haven't tested it at all yet because the testbench for the other two is still controlling the control signals in SIM.cpp so we either need to test them in separate top functions or synchronize the testbenches with a common clk tick.
